import nucleotide

Import('settings')


# Accumulate Atoms

## Enable exceptions
settings.accumulate( 'exception' )

## Set Run Time Library
settings.accumulate( 'blank' )
settings.accumulate( 'include', { '0' : '../../../../src' } )  

# Accumulate source
source = []
source +=   ['eigen_test.cpp']
source +=   ['invert_test.cpp']
source +=   ['test.cpp']

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
